// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/availability">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/packages">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/videos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/videos">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/videos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/packages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/gallery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/gallery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/availability/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/availability/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/availability/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
